// Full Artificios repertoire — keep in sync with site.html
// [title, artist, year, vibe]  — vibe in: pop, rock, dance, balada, synth, latin
window.ARTIFICIOS_SONGS = [
  ["A Little Respect","Erasure",1988,"synth"],
  ["Baby Come Back","Player",1977,"pop"],
  ["Careless Whisper","George Michael",1984,"balada"],
  ["Don't You Want Me","Human League",1981,"synth"],
  ["Easy Lover","Phil Collins",1984,"pop"],
  ["Everybody Wants to Rule the World","Tears for Fears",1985,"pop"],
  ["Hold the Line","Toto",1978,"rock"],
  ["I Just Called to Say I Love You","Stevie Wonder",1984,"balada"],
  ["I Want to Break Free","Queen",1984,"rock"],
  ["Is This Love","Whitesnake",1987,"rock"],
  ["Baby Jane","Rod Stewart",1983,"pop"],
  ["Maniac","Michael Sembello",1983,"dance"],
  ["Say Say Say","Michael Jackson & Paul McCartney",1983,"pop"],
  ["Take On Me","A-Ha",1985,"synth"],
  ["Your Love","The Outfield",1985,"rock"],
  ["Square Rooms","Al Corley",1984,"synth"],
  ["Never Gonna Give You Up","Rick Astley",1987,"pop"],
  ["Africa","Toto",1982,"rock"],
  ["Talking in Your Sleep","The Romantics",1983,"rock"],
  ["Should I Stay or Should I Go","The Clash",1982,"rock"],
  ["Stop!","Erasure",1991,"synth"],
  ["It Ain't Over Till It's Over","Lenny Kravitz",1991,"rock"],
  ["Watermelon Sugar","Harry Styles",2019,"pop"],
  ["Boys Don't Cry","The Cure",1979,"synth"],
  ["Sledgehammer","Peter Gabriel",1986,"pop"],
  ["Eye of the Tiger","Survivor",1982,"rock"],
  ["Eyes Without a Face","Billy Idol",1984,"rock"],
  ["(I Just) Died in Your Arms","Cutting Crew",1986,"rock"],
  ["Mystify","INXS",1987,"rock"],
  ["Locked Out of Heaven","Bruno Mars",2012,"pop"],
  ["Big in Japan","Alphaville",1984,"synth"],
  ["Lady (Hear Me Tonight)","Modjo",2000,"dance"],
  ["Just an Illusion","Imagination",1982,"dance"],
  ["Last Train to London","ELO",1979,"dance"],
  ["Wicked Game","Chris Isaak",1989,"balada"],
  ["Rock with You","Michael Jackson",1979,"dance"],
  ["Never Tear Us Apart","INXS",1987,"rock"],
  ["I Want to Know What Love Is","Foreigner",1984,"balada"],
  ["I Was Born to Love You","Queen",1985,"rock"],
  ["Blinding Lights","The Weeknd",2019,"pop"],
  ["The Power of Love","Huey Lewis & The News",1985,"rock"],
  ["I Feel It Coming","The Weeknd ft. Daft Punk",2016,"pop"],
  ["It Must Have Been Love","Roxette",1990,"balada"],
  ["Stars","Simply Red",1991,"pop"],
  ["Ladies' Night","Kool & The Gang",1979,"dance"],
  ["Don't Dream It's Over","Crowded House",1986,"pop"],
  ["Easy","Commodores / Faith No More",1977,"balada"],
  ["The Final Countdown","Europe",1986,"rock"],
  ["Eye in the Sky","Alan Parsons Project",1982,"rock"],
  ["Head Over Heels","Tears for Fears",1985,"pop"],
  ["Billie Jean","Michael Jackson",1983,"dance"],
  ["You Give Love a Bad Name","Bon Jovi",1986,"rock"],
  ["Always on the Run","Lenny Kravitz",1991,"rock"],
  ["Purple Rain","Prince",1984,"balada"],
  ["Sure Know Something","Kiss",1979,"rock"],
  ["It's My Life","Talk Talk",1984,"synth"],
  ["Anybody Seen My Baby?","Rolling Stones",1997,"rock"],
  ["Strangelove","Depeche Mode",1987,"synth"],
  ["Do I Wanna Know?","Arctic Monkeys",2013,"rock"],
  ["Karma Chameleon","Culture Club",1983,"pop"],
  ["Luna de Miel en la Mano","Virus",1985,"latin"],
  ["Nos Siguen Pegando Abajo","Charly García",1989,"latin"],
  ["Departamento","Bándalos Chinos",2018,"latin"],
  ["What's Love Got to Do with It","Tina Turner",1984,"pop"],
  ["The Look","Roxette",1988,"pop"],
  ["Girls Just Wanna Have Fun","Cyndi Lauper",1983,"pop"],
  ["Caribbean Queen","Billy Ocean",1984,"pop"],
  ["I Was Made for Lovin' You","Kiss",1979,"rock"],
  ["West End Girls","Pet Shop Boys",1984,"synth"],
  ["I Can't Go for That (No Can Do)","Hall & Oates",1981,"pop"],
  ["Every Time You Go Away","Paul Young",1985,"balada"],
  ["No Sé Tú / Cuando Calienta el Sol","Luis Miguel",1990,"latin"],
  ["Y.M.C.A.","Village People",1978,"dance"],
  ["Nothing's Gonna Stop Us Now","Starship",1987,"balada"],
  ["Te Quiero Tanto","Sergio Denis",1983,"latin"],
  ["Crazy Little Thing Called Love","Queen",1979,"rock"],
  ["Celebration","Kool & The Gang",1980,"dance"],
  ["Lady in Red","Chris de Burgh",1986,"balada"],
  ["Low","Lenny Kravitz",2018,"rock"],
  ["Kiss on My List","Hall & Oates",1980,"pop"],
  ["The Way It Is","Bruce Hornsby",1986,"balada"],
  ["Just Like Heaven","The Cure",1987,"synth"],
  ["Broken Wings","Mr. Mister",1985,"balada"],
  ["Superstition","Stevie Wonder",1972,"dance"],
  ["I Belong to You","Lenny Kravitz",1998,"rock"],
  ["Somebody's Watching Me","Rockwell",1984,"synth"],
  ["Under Pressure","Queen & Bowie",1981,"rock"],
  ["Miss Me Blind","Culture Club",1983,"pop"],
  ["Waiting for a Girl Like You","Foreigner",1981,"balada"],
  ["Adore You","Harry Styles",2019,"pop"],
  ["Overkill","Men at Work",1983,"rock"],
  ["Faith","George Michael",1987,"pop"],
  ["Maneater","Hall & Oates",1982,"pop"],
  ["Lovesong","The Cure",1989,"synth"],
  ["Still Got the Blues","Gary Moore",1990,"balada"],
  ["Money for Nothing","Dire Straits & Sting",1985,"rock"],
  ["Gold","Chet Faker",2014,"pop"],
  ["True","Spandau Ballet",1983,"balada"],
  ["Mr. Blue Sky","ELO",1977,"pop"],
  ["Give Life Back to Music","Daft Punk",2013,"dance"],
  ["So Lonely","The Police",1978,"rock"],
  ["Part-Time Lover","Stevie Wonder",1985,"pop"],
  ["Self Control","Laura Branigan",1984,"synth"],
  ["Sweet Dreams","Eurythmics",1983,"synth"],
  ["Smalltown Boy","Bronski Beat",1984,"synth"],
  ["Enjoy the Silence","Depeche Mode",1990,"synth"],
  ["There's No Easy Way Out","Robert Tepper",1985,"rock"],
  ["Ghostbusters","Ray Parker Jr.",1984,"pop"],
  ["Feel","Robbie Williams",2002,"pop"],
].map(([title,artist,year,vibe], i) => ({ id: i, title, artist, year, vibe }));

window.VIBE_LABEL = { pop:"Pop", rock:"Rock", dance:"Dance", balada:"Balada", synth:"Synth", latin:"Español" };
